### ISSUE TITLE
Compilation requires c89

### ISSUE THREAD

**Issue by caseyduquettesc** [robxu9/bash-static#17]
If I try to build on macos 11.5, bash 3.2 and 4.4 fail because of implicit function declarations. Bash 5.1 works ok.

Based on this - https://www.gnu.org/software/bash/manual/html_node/Compilers-and-Options.html, the solution seems to be to enable c89 mode.

```
./support/bashversion.c:138:21: error: implicit declaration of function 'shell_version_string' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    printf ("%s\n", shell_version_string ());
                    ^
./support/bashversion.c:140:5: error: implicit declaration of function 'show_shell_version' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    show_shell_version (0);
    ^
```

**Comment by robxu9** [comment]
Hmm, I'm sort of reluctant to support this because I wanted this repo to continue to support the latest versions of bash only. Is there a particular use case for continuing to support bash 3.2 or 4.4?

**Comment by caseyduquettesc** [comment]
Yeah, that's fair. I'm on a dev-ops team and MacOS still ships with bash 3 by default. We have a tool written in bash that is deployed on our devs laptops and I wanted to run the unit tests against a bash 3 binary embedded in the project so that someone working on it doesn't add bash 4/5-only code just because it works on their laptops.

**Comment by robxu9** [comment]
Ah, fair enough - macOS is still being stuck on old bash versions continue to be a pain, lol. I'll merge this and I'll consider releasing 3.2/4.4 versions of bash-static.
