### ISSUE TITLE
Cannot build bash-5.2 (`strtoimax` related error)

### ISSUE THREAD

**Issue by nukemiko** [robxu9/bash-static#39]
Distro: Arch Linux

Using the latest build scripts.

Commands and outputs:

```sh-session
> ./build.sh linux x86_64
[...]
/home/miketsu/Projects/bash-static/build/musl-install/bin/musl-gcc -L./builtins -L./lib/readline -L./lib/readline -L./lib/glob -L./lib/tilde  -L./lib/sh  -L./lib/termcap -rdynamic -static -Os   -o bash shell.o eval.o y.tab.o general.o make_cmd.o print_cmd.o  dispose_cmd.o execute_cmd.o variables.o copy_cmd.o error.o expr.o flags.o jobs.o subst.o hashcmd.o hashlib.o mailcheck.o trap.o input.o unwind_prot.o pathexp.o sig.o test.o version.o alias.o array.o arrayfunc.o assoc.o braces.o bracecomp.o bashhist.o bashline.o  list.o stringlib.o locale.o findcmd.o redir.o pcomplete.o pcomplib.o syntax.o xmalloc.o  -lbuiltins -lglob -lsh -lreadline -lhistory ./lib/termcap/libtermcap.a -ltilde     -ldl 
/usr/bin/ld: /home/miketsu/Projects/bash-static/build/musl-install/lib/libc.a(strtol.lo): in function `strtoimax':
strtol.c:(.text.strtoimax+0x0): multiple definition of `strtoimax'; ./lib/sh/libsh.a(strtoimax.o):strtoimax.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:595: bash] Error 1
```
I can successfully build bash-5.1.16 using the same build script, but I cannot build bash-5.2, instead I get the above error.

**Comment by robxu9** [comment]
Sorry for the delay! I'm working on getting 5.2.15 tagged and out right now.
